#### 1. Решите линейную систему:
###### $A * X = B$

$\left( \begin{array} { c c c } { 1 } & { 2 } & { 3 } \\ { 4 } & { 0 } & { 6 } \\ { 7 } & { 8 } & { 9 } \end{array} \right) \left( \begin{array} \ x_1 \\ x_2 \\ x_3 \end{array} \right) = \left( \begin{array} \ 12 \\ 2 \\ 1 \end{array} \right)$

In [1]:
import numpy as np
from numpy import linalg
import warnings
warnings.filterwarnings("ignore")

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

In [3]:
X = np.linalg.solve(A, B)
print(f'Решение: X = {X}')

Решение: X = [-9.2         0.9         6.46666667]


#### 2. Найдите псевдорешение:
$\begin{array} \ x + 2y – z = 1 \\ 3x – 4y = 7 \\ 8x – 5y + 2z = 12 \\ 2x – 5z = 7 \\ 11x +4y – 7z = 15 \end{array}$

In [4]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])

In [5]:
print(np.linalg.matrix_rank(A))

3


In [6]:
solution = np.linalg.lstsq(A, B)
solution

(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [7]:
print(f'Псевдорешение = {solution[0]}')

Псевдорешение = [ 1.13919353 -0.90498444 -0.9009803 ]


In [8]:
print(f'Невязка = {np.dot(A, [ 1.13919353, -0.90498444, -0.9009803 ]) - B}')

Невязка = [-0.76979505  0.03751835 -0.16349016 -0.21671144  0.21805317]


In [9]:
print(f'Значение функции невязки = {(np.linalg.norm(np.dot(A, [ 1.13919353, -0.90498444, -0.9009803 ]) - B))**2}')

Значение функции невязки = 0.7152321111819737


#### 3. Сколько решений имеет линейная система:
$\left( \begin{array} { c c c } { 1 } & { 2 } & { 3 } \\ { 4 } & { 5 } & { 6 } \\ { 7 } & { 8 } & { 9 } \end{array} \right) \left( \begin{array} \ x_1 \\ x_2 \\ x_3 \end{array} \right) = \left( \begin{array} \ 12 \\ 2 \\ 1 \end{array} \right)$
#### Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

In [11]:
np.linalg.det(A)

-9.51619735392994e-16

$\ то \ есть \ det(A) = 0$

In [12]:
print(f'Ранг исходной матрицы = {np.linalg.matrix_rank(A)}')

Ранг исходной матрицы = 2


In [13]:
B1 = np.array([[12, 2, 1]])
C = np.concatenate((A, B1.T), axis=1)
print(f'Ранг расширеной матрицы = {np.linalg.matrix_rank(C)}')

Ранг расширеной матрицы = 3


Т.к. ранг исходной матрицы = 2, а ранг расширенной матрицы = 3 => система несовместна.

In [14]:
B2 =  np.array([1, 1, 1])
B22 = np.matrix(B2)
print(f'Новый вектор правой части: B = {B2}')
C2 = np.concatenate((A, B22.T), axis=1)
print(f'Ранг расширеной матрицы = {np.linalg.matrix_rank(C2)}')

Новый вектор правой части: B = [1 1 1]
Ранг расширеной матрицы = 2


In [15]:
solution = np.linalg.lstsq(A, B2)
solution

(array([-5.00000000e-01,  3.07361416e-16,  5.00000000e-01]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))

In [16]:
print(f'Псевдорешение = {[-0.5, 0, 0.5]}')

Псевдорешение = [-0.5, 0, 0.5]


#### 4. Вычислите LU-разложение матрицы:
$\left( \begin{array} { c c c } { 1 } & { 2 } & { 3 } \\ { 2 } & { 16 } & { 21 } \\ { 4 } & { 28 } & { 73 } \end{array} \right)$
#### После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [17]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])

In [18]:
import scipy, scipy.linalg

P, L, U = scipy.linalg.lu(A)

In [19]:
print(P)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [20]:
print(L)

[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]


In [21]:
print(U)

[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [22]:
print(np.dot(L, U))

[[ 4. 28. 73.]
 [ 1.  2.  3.]
 [ 2. 16. 21.]]


In [23]:
np.linalg.det(A)

432.00000000000017

In [24]:
B = np.array([1, 1, 1])
print(f'Вектор правой части B = {B}')

Вектор правой части B = [1 1 1]


In [25]:
Y = np.linalg.solve(L, B)
print(f'Y = {Y}')

Y = [1.   0.75 0.8 ]


In [26]:
X = np.linalg.solve(U, Y)
print(f'Решение: X = {X}')

Решение: X = [ 1.18518519 -0.03703704 -0.03703704]


In [27]:
print(f'Проверка B = {np.dot(A, X)}')

Проверка B = [1. 1. 1.]


#### 5. Найдите нормальное псевдорешение недоопределенной системы:
$\begin{array} \ x + 2y – z = 1 \\ 8x – 5y + 2z = 12 \end{array}$
#### Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 

In [28]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])

In [29]:
Q, R = np.linalg.qr(A)

In [30]:
print(Q)

[[-0.12403473 -0.99227788]
 [-0.99227788  0.12403473]]


In [31]:
print(R)

[[-8.06225775  4.71331991 -1.86052102]
 [ 0.         -2.60472943  1.24034735]]


In [32]:
print(np.dot(Q, R))

[[ 1.  2. -1.]
 [ 8. -5.  2.]]


In [33]:
R1 = R[:2, :2]
R1

array([[-8.06225775,  4.71331991],
       [ 0.        , -2.60472943]])

In [34]:
B1 = np.dot(Q.T, B)
B1

array([-12.03136926,   0.49613894])

In [35]:
X1 = np.linalg.solve(R1, B1)
print(f'Решение: X1 = {X1}')

Решение: X1 = [ 1.38095238 -0.19047619]


In [36]:
X = np.append(X1, 0)
print(f'Псевдорешение: X = {X}')

Псевдорешение: X = [ 1.38095238 -0.19047619  0.        ]


In [37]:
np.linalg.norm(X)

1.3940267779337572

In [38]:
np.linalg.norm(np.dot(A, X) - B)

1.5543122344752192e-15

#### 6. Найдите одно из псевдорешений вырожденной системы:
$\left( \begin{array} { c c c } { 1 } & { 2 } & { 3 } \\ { 4 } & { 5 } & { 6 } \\ { 7 } & { 8 } & { 9 } \end{array} \right) \left( \begin{array} \ x_1 \\ x_2 \\ x_3 \end{array} \right) = \left( \begin{array} \ 2 \\ 5 \\ 11 \end{array} \right)$
#### Попробуйте также отыскать и нормальное псевдорешение.

In [39]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])

In [40]:
np.linalg.det(A)

-9.51619735392994e-16

In [41]:
solution = np.linalg.lstsq(A, B)

In [42]:
print(f'Псевдорешение = {solution[0]}')

Псевдорешение = [ 1.25  0.5  -0.25]


In [43]:
X = solution[0]
X

array([ 1.25,  0.5 , -0.25])

In [44]:
np.linalg.norm(np.dot(A, X) - B)

1.224744871391589